version: '3'
services:

  backend:
    volumes:
      - ./backend/src:/app/src
      - ./shared:/app/src/shared
      - dist_2:/app/dist
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3030:3030
      - 8001:8001
    depends_on:
      - frontend

  frontend:
    volumes:
      - ./frontend/src:/app/src
      - ./shared:/app/src/shared
      - ./frontend/public:/app/public
      - dist_2:/app/dist
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - HOST=${HOST}

volumes:
  dist_2:
